### PR TITLE
flutter 2.0

### PR DESCRIPTION
**Pull request by redDwarf03**

### CODE REVIEW

**Comment by tejainece** [comment]
@litaoh Can you please merge and publish it?

**Comment by redDwarf03** [comment]
try this for the moment: https://github.com/redDwarf03/hash.git

**Comment by tejainece** [comment]
@redDwarf03 i would like to publish a package to pub that depends on this package.

**Comment by redDwarf03** [comment]
If you want, I can publish a « hash2 » to pub and I will delete it when hash will be updated

**Comment by litaoh** [comment]
> If you want, I can publish a « hash2 » to pub and I will delete it when hash will be updated

You can publish < hash2 > to pubs

**Pull request merged**
